### ISSUE TITLE
Articles on HTML/CSS

### ISSUE THREAD

**Issue by yunaimatsu** [yunaimatsu/yunaimatsu#6]
# 画像
```html
<img src="example.jpg" />
```
# 音声
```html
<audio src="example.mp3"></audio>
```
# 動画
```html
<video src="example.mp4"></video>
```
# 独立したコンテンツ
```html
<figure>
    <img src="example.jpg" />
    <figcaption>Caption</figcaption>
</figure>
```
# ファイル全般・選択可能なファイルを複数指定
```html
<source src="example.mp4" />
```

# 字幕
```html
<track src="example.vtt" />
```

# アプリの埋め込み
```html
<embed src="example.swf" />
```

# 他サイト
```html
<iframe src="https://example.com"></iframe>
```

# 「クリッカブルマップ」
「クリッカブルマップ」とは、リンクを埋め込ませてクリックできる図形のことです。
```html
<map name="example-map">
    <area shape="rect" coords="34,44,270,350" href="example.html" alt="Example" />
</map>
<img src="example.jpg" usemap="#example-map" />
```

---
layout: '@layout/Layout.astro'
---

```css
p {
    text-decoration-line: ;
    text-decoration-color: ;
    text-decoration-style: ;
    text-decoration-thickness: ;

    text-decoration: ;
}
```
```css
p {
    text-underline-position: ;
}
```
```css
p {
    text-emphasis-style: ;
    text-emphasis-color: ;
    text-emphasis: ;
}
```
```css
p {
    text-emphasis-position: ;
}
```%
