### ISSUE TITLE
Transplant old sections in README

### ISSUE THREAD

**Issue by yunaimatsu** [yunaimatsu/yunaimatsu#71]
Oh, I have to transplant the following part which was written in README previously

以下のパートは、 yunaimatsu/yunaimatsu#56 で実現可能。
```
# WISH LIST
共立出版: 情報系のための離散数学
森北出版: グラフ理論入門-基本とアルゴリズム-
近代科学社: グラフ理論入門
講談社: イラストで学ぶ離散数学
数研出版: 大学教養統計学
ナツメ社: これならわかる！ベイズ統計学
東京電機大学出版局: 形式言語理論入門
コンピューター言語 進化論
オートマトの言語理論 森北出版
講談社サイエンティフィック 自然言語とコンピューター言語
```
以下のパートは、吟味が必要。
1. 現在のこのプロジェクトのディレクトリ構成とは異なるものになっているから。
2. 本当にここに記載するべきものじゃない気がするから(Wikiに追加しよう!)。
```
## Website framework(`Layout`)
1. Header
	a. Go back to `home/`
	b. Multilingual-available button
	c. Link to `a/`
	d. Link to `b/`
	e. Link to `c/`
2. Main
	a. Top(そのページの題名を表す)
	b. Save this page as...
		i. PDF
		ii. MD
		iii. HTML
	blogの説明
	blogのデザインの説明
	各ジャンルの説明
3. Footer
	a. Detail link to `a/`
	b. Detail link to `b/`
	c. Detail link to `c/`

## Website Contents
`c`: link to /c(contact, provide a clear way for potential clients to reach you)

## Website Design(Theme)
- Opt
    
    `+layout.svelte` `Layout.astro`のみで以下のメタ情報を記入する。
    
    他の場所ではインポート不要。
    
    ```tsx
    import 'path/to/global.css';
    ```
    
    `global.css`
    
    ```css
    @import 'image.css'
    @import 'image.css'
    @import 'image.css'
    @import 'image.css'
    @import 'image.css'
    @import 'image.css'
    @import 'image.css'
    @import 'image.css'
    @import 'image.css'
    @import 'image.css'
    @import 'image.css'
    @import 'image.css'
    ```
    
    なるべくcomponentに細かく分ける
    
    How to organize CSS
    
    CSSは
    
    インポートは単純化する
    
    `+page.svelte`はComponentだけにする
    
    global.cssをインポートするだけでいいようにしよう。
    
- Toggle-options
    
    俺のHPへのリンクを貼ってもいいですか？
    
- Selection-options
    
    テーマカラーの数、カラーコード
    
    常にいろんなWebフレームワークを調べよう。そして常に最高のものを手元に用意しておこう。
    
    - `image.css`
        - はみ出ないようにする`width: 100%;`
        - サイトの雰囲気を壊さないように明るさや色味をデフォルトで買えるようにする。
    - `font.css`
        - font-family（ダサくないフォントはおすすめはしよう）
        - 太さ
        - 色
        - 選択した
    - `selection.css`
        
        ```css
        ::selection {
          background-color: #ffcc00; /* Set background color to yellow */
          color: #000000;            /* Set text color to black */
        }
        
        /* Vendor prefix for Firefox */
        ::-moz-selection {
          background-color: #ffcc00;
          color: #000000;
        }
        ```
        
- Default
    - `image.css`
        
        ```css
        img {
            max-width: 100%; /* This will make the image take the full width of its parent container */
            height: auto; /* This will maintain the aspect ratio of the image */
        }
        ```
        
    - `link.css`
        - 最低限decorationはなくす。
        - 踏んだリンクの色変わるのもなくす。
        
        ```css
        a {
          text-decoration: none; /* Remove the underline */
          color: inherit; /* Match the link color to the parent element's color */
        }
        
        a:visited {
          color: inherit; /* Do not change the color of visited links */
        }
        ```
        
    - `list.css`
        - listマーク消す
        
        ```css
        ul, ol {
          list-style-type: none; /* Remove the list markers */
          padding-left: 0; /* Remove the default indentation (optional) */
          margin: 0; /* Remove default margin (optional) */
        }
        ```
```

_Originally posted by @yunaimatsu in https://github.com/yunaimatsu/website/issues/4#issuecomment-2568623196_
